name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test with pytest
        run: |
          echo "Ignoring tensorflow dependencies..."
          sed '/tensorflow/d' pyproject.toml > pyproject2.toml
          mv pyproject2.toml pyproject.toml
          cat pyproject.toml
          pip install poetry
          poetry run pip install --upgrade pip
          poetry lock
          poetry install
          poetry run ls
          poetry run pytest dqn_tictactoe
